name: Taskwell Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend
        run: cd backend && ./gradlew clean build
            
      - name: Test Backend
        run: cd backend && ./gradlew test

  frontend:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Test Frontend
        run: cd frontend && npx jest
